language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
env:
  BASEPATH: "/react-reach-barebones"
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
